-- HabitLoop schema; default database: nodejs_demo
-- Additive migration only. Runtime also seeds hl_meta cursor_signing_key.

CREATE TABLE IF NOT EXISTS hl_meta (name VARCHAR(64) PRIMARY KEY,value TEXT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS hl_users (identity_key CHAR(64) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,owner_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,document JSON NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `hl_tasks` (id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,owner_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,task_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,round_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,business_date CHAR(10) CHARACTER SET ascii COLLATE ascii_bin NULL,sort_at VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,document JSON NOT NULL,KEY idx_owner_sort(owner_id,sort_at,id),KEY idx_task_sort(owner_id,task_id,sort_at,id),KEY idx_round(owner_id,task_id,round_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `hl_task_rules` (id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,owner_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,task_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,round_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,business_date CHAR(10) CHARACTER SET ascii COLLATE ascii_bin NULL,sort_at VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,document JSON NOT NULL,KEY idx_owner_sort(owner_id,sort_at,id),KEY idx_task_sort(owner_id,task_id,sort_at,id),KEY idx_round(owner_id,task_id,round_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `hl_rounds` (id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,owner_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,task_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,round_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,business_date CHAR(10) CHARACTER SET ascii COLLATE ascii_bin NULL,sort_at VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,document JSON NOT NULL,KEY idx_owner_sort(owner_id,sort_at,id),KEY idx_task_sort(owner_id,task_id,sort_at,id),KEY idx_round(owner_id,task_id,round_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `hl_checkins` (id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,owner_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,task_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,round_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,business_date CHAR(10) CHARACTER SET ascii COLLATE ascii_bin NULL,sort_at VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,document JSON NOT NULL,KEY idx_owner_sort(owner_id,sort_at,id),KEY idx_task_sort(owner_id,task_id,sort_at,id),KEY idx_round(owner_id,task_id,round_id),UNIQUE KEY uniq_daily(owner_id,task_id,business_date)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `hl_points_ledger` (id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,owner_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,task_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,round_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,business_date CHAR(10) CHARACTER SET ascii COLLATE ascii_bin NULL,sort_at VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,document JSON NOT NULL,KEY idx_owner_sort(owner_id,sort_at,id),KEY idx_task_sort(owner_id,task_id,sort_at,id),KEY idx_round(owner_id,task_id,round_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `hl_goal_claims` (id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,owner_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,task_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,round_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,business_date CHAR(10) CHARACTER SET ascii COLLATE ascii_bin NULL,sort_at VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,document JSON NOT NULL,KEY idx_owner_sort(owner_id,sort_at,id),KEY idx_task_sort(owner_id,task_id,sort_at,id),KEY idx_round(owner_id,task_id,round_id),UNIQUE KEY uniq_claim(owner_id,round_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `hl_command_receipts` (id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,owner_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,task_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,round_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,business_date CHAR(10) CHARACTER SET ascii COLLATE ascii_bin NULL,sort_at VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,document JSON NOT NULL,KEY idx_owner_sort(owner_id,sort_at,id),KEY idx_task_sort(owner_id,task_id,sort_at,id),KEY idx_round(owner_id,task_id,round_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `hl_outbox_events` (id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,owner_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,task_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,round_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,business_date CHAR(10) CHARACTER SET ascii COLLATE ascii_bin NULL,sort_at VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,document JSON NOT NULL,KEY idx_owner_sort(owner_id,sort_at,id),KEY idx_task_sort(owner_id,task_id,sort_at,id),KEY idx_round(owner_id,task_id,round_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `hl_export_jobs` (id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,owner_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,task_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,round_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,business_date CHAR(10) CHARACTER SET ascii COLLATE ascii_bin NULL,sort_at VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,document JSON NOT NULL,KEY idx_owner_sort(owner_id,sort_at,id),KEY idx_task_sort(owner_id,task_id,sort_at,id),KEY idx_round(owner_id,task_id,round_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `hl_notification_jobs` (id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,owner_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,task_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,round_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,business_date CHAR(10) CHARACTER SET ascii COLLATE ascii_bin NULL,sort_at VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,document JSON NOT NULL,KEY idx_owner_sort(owner_id,sort_at,id),KEY idx_task_sort(owner_id,task_id,sort_at,id),KEY idx_round(owner_id,task_id,round_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
